on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # [macOS-latest]
        ghc: ['8.10.7']
        agda: ['2.6.1.3']

    steps:


    # Checkout

    - name: Checkout
      uses: actions/checkout@v2
      with:
        # ref: dev
        # fetch-depth: 1
        submodules: true


    # Setup & Cache Haskell

    - name: Cache Haskell
      uses: actions/cache@v2
      id: cache-haskell
      with:
        path: |
          ~/.ghcup
        key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}


    - name: Setup Haskell
      if: steps.cache-haskell.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
        stack-version: 'latest'
      id: haskell-setup

    - name: Update stack.yaml
      run: |
        stack config set system-ghc true
        stack config set install-ghc false
      shell: bash

    - name: Info about the setup
      shell: bash
      run: |
        echo "runner.os   = ${{ runner.os }}"
        echo "ghc-path    = ${{ steps.haskell-setup.outputs.ghc-path    }}"
        echo "cabal-path  = ${{ steps.haskell-setup.outputs.cabal-path  }}"
        echo "stack-path  = ${{ steps.haskell-setup.outputs.stack-path  }}"
        echo "cabal-store = ${{ steps.haskell-setup.outputs.cabal-store }}"
        echo "ghc-exe     = ${{ steps.haskell-setup.outputs.ghc-exe     }}"
        echo "cabal-exe   = ${{ steps.haskell-setup.outputs.cabal-exe   }}"
        echo "stack-exe   = ${{ steps.haskell-setup.outputs.stack-exe   }}"
        echo "stack-root  = ${{ steps.haskell-setup.outputs.stack-root  }}"
        echo "STACK_VER=$(stack --numeric-version)" >> ${GITHUB_ENV}
        echo "GHC_VER=$(ghc --numeric-version)" >> ${GITHUB_ENV}

    - name: Haskell versions
      shell: bash
      run: |
        echo "GHC_VER     = ${{ env.GHC_VER   }}"
        echo "STACK_VER   = ${{ env.STACK_VER }}"
        # echo "STACK_YAML=stack-${{ env.GHC_VER }}.yaml" >> ${GITHUB_ENV}
        # echo "STACK_FLAGS=--stack-yaml stack-${{ env.GHC_VER }}.yaml --system-ghc --no-terminal --color always" >> ${GITHUB_ENV}

    # Setup & Cache HTMLProofer

    - name: Get Ruby Info
      id: ruby-info
      run: |
        echo "::set-output name=ruby::$(ruby -e 'puts RUBY_VERSION')"
        echo "::set-output name=gem::$(gem --version)"
        echo "::set-output name=gemdir::$(gem env gemdir)"
      shell: bash

    - name: Cache HTMLProofer
      uses: actions/cache@v2
      id: cache-htmlproofer
      with:
        path: ${{ steps.ruby-info.outputs.gemdir }}
        key: ${{ matrix.os }}-ruby-${{ steps.ruby-info.outputs.ruby }}-gem-${{ steps.ruby-info.outputs.gem }}

    - name: Setup HTMLProofer
      if: steps.cache-htmlproofer.outputs.cache-hit != 'true'
      run: sudo gem install html-proofer
      shell: bash


    - name: Prepare Agda standard library
      run: |
        cabal update
        cd standard-library
        cabal run --allow-newer GenerateEverything
        cd ..
      shell: bash

    # Setup & Cache Agda, pandoc, and site builder

    - name: Cache .stack-work
      uses: actions/cache@v2
      id: cache-stack-work
      with:
        path: $GITHUB_WORKSPACE/.stack-work
        key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-agda-${{ matrix.agda }}

    - name: Update stack
      run: stack update --silent

    - name: Build Agda
      if: steps.cache-site-builder.outputs.cache-hit != 'true'
      run: stack build Agda-${{ matrix.agda }}
      shell: bash

    # To avoid locked .agdai files when building the site,
    # we precompile the .agdai files of the standard library.
    - name: Build standard-library
      run: stack exec --cwd standard-library agda -- -i . -i src Everything.agda
      shell: bash

    - name: Build Pandoc
      if: steps.cache-site-builder.outputs.cache-hit != 'true'
      run: stack build pandoc
      shell: bash

    - name: Build other dependencies
      if: steps.cache-site-builder.outputs.cache-hit != 'true'
      run: stack build --only-dependencies
      shell: bash

    - name: Build Site Builder
      if: steps.cache-site-builder.outputs.cache-hit != 'true'
      run: stack build
      shell: bash


    # Build & Test Website

    - name: Build Website
      run: make build
      shell: bash

    - name: Test Website
      run: make test
      shell: bash
